<template>
  <component
    :is="IconComponent"
    class="app-icon"
    :size="Number(size)"
    :stroke-width="strokeWidth"
    aria-hidden="true"
  />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  BadgeCheck,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Boxes,
  Brain,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  Check,
  ClipboardList,
  Clock,
  Coffee,
  Coins,
  Cpu,
  CreditCard,
  Database,
  Download,
  Eye,
  EyeOff,
  FileText,
  FlaskConical,
  Gauge,
  HardDrive,
  History,
  Keyboard,
  Key,
  Layers,
  LayoutDashboard,
  Lock,
  LogOut,
  Maximize2,
  Menu,
  Minimize2,
  MinusCircle,
  Monitor,
  Moon,
  Package,
  Palette,
  Pencil,
  Plus,
  Printer,
  Receipt,
  ReceiptText,
  RefreshCw,
  Save,
  Scale,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sliders,
  SlidersHorizontal,
  Sparkles,
  Store,
  Sun,
  Tag,
  Tags,
  Timer,
  TimerOff,
  Trash2,
  TrendingDown,
  TrendingUp,
  Truck,
  Upload,
  UserCheck,
  UserCog,
  Users,
  UtensilsCrossed,
  Volume2,
  WalletCards,
  Warehouse,
  X,
  Zap,
} from '@lucide/vue';

const props = defineProps({
  name: { type: String, default: 'dashboard' },
  size: { type: [Number, String], default: 20 },
  strokeWidth: { type: [Number, String], default: 2 },
});

const icons: Record<string, any> = {
  // Navigation & Core
  dashboard: LayoutDashboard,
  gauge: Gauge,
  shop: Store,
  sales: ReceiptText,
  coffee: Coffee,
  zap: Zap,
  bot: Bot,
  cpu: Cpu,
  products: Package,
  purchases: ShoppingCart,
  inventory: Boxes,
  costs: Calculator,
  recipes: ClipboardList,
  stocktake: ClipboardList,
  customers: Users,
  invoices: FileText,
  quote: FileText,
  quotes: UtensilsCrossed,
  expenses: WalletCards,
  suppliers: Truck,
  reports: BarChart3,
  users: ShieldCheck,
  settings: Settings,
  operations: Activity,
  hr: Briefcase,
  search: Search,
  money: WalletCards,
  cash: Banknote,
  wallet: WalletCards,
  building: Building2,
  company: Building2,
  categories: Layers,
  category: Tag,
  tags: Tags,
  tag: Tag,
  unit: Scale,
  units: Scale,
  scale: Scale,
  sound: Volume2,
  volume: Volume2,
  shortcuts: Keyboard,
  keyboard: Keyboard,
  backup: HardDrive,
  database: Database,
  history: History,
  lock: Lock,
  shield: Shield,
  print: Printer,
  printer: Printer,
  palette: Palette,
  theme: Palette,
  monitor: Monitor,
  warehouse: Warehouse,
  flask: FlaskConical,
  send: Send,
  brain: Brain,
  bell: Bell,
  upload: Upload,
  download: Download,
  plus: Plus,
  add: Plus,
  edit: Pencil,
  delete: Trash2,
  trash: Trash2,
  save: Save,
  close: X,
  check: Check,
  warning: AlertTriangle,
  moon: Moon,
  sun: Sun,
  menu: Menu,
  logout: LogOut,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowRightLeft: ArrowRightLeft,
  calendar: Calendar,
  clock: Clock,
  coins: Coins,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  userCheck: UserCheck,
  userCog: UserCog,
  receipt: Receipt,
  copilot: Sparkles,
  eye: Eye,
  eyeOff: EyeOff,
  maximize: Maximize2,
  minimize: Minimize2,
  timer: Timer,
  timerOff: TimerOff,
  refresh: RefreshCw,
  refreshCw: RefreshCw,
  minusCircle: MinusCircle,
  fileText: FileText,
  activity: Activity,
  sliders: SlidersHorizontal,
  shoppingBag: ShoppingBag,
  bookOpen: BookOpen,
  badge: BadgeCheck,
  creditCard: CreditCard,
  key: Key,
};

const aliases: Record<string, string> = {
  // Alias mappings (Material design -> Lucide & common names)
  '+': 'plus',
  product: 'products',
  invoice: 'invoices',
  supplier: 'suppliers',
  expense: 'expenses',
  user: 'users',
  chart: 'reports',
  calculator: 'costs',
  'file-text': 'fileText',
  'refresh-cw': 'refreshCw',
  'minus-circle': 'minusCircle',
  'arrow-left': 'arrowLeft',
  'arrow-right': 'arrowRight',
  'trending-up': 'trendingUp',
  'trending-down': 'trendingDown',
  'eye-off': 'eyeOff',
  'timer-off': 'timerOff',
  pos: 'shop',
  shopping_cart: 'purchases',
  inventory_2: 'inventory',
  sync_alt: 'refreshCw',
  shopping_bag: 'shoppingBag',
  payments: 'money',
  group: 'customers',
  local_shipping: 'suppliers',
  menu_book: 'recipes',
  bar_chart: 'reports',
  manage_accounts: 'userCog',
  sell: 'category',
};

const IconComponent = computed(() => {
  const raw = props.name || 'dashboard';
  const key = aliases[raw] || raw;
  return icons[key] || icons.dashboard;
});
</script>

<style scoped>
.app-icon {
  width: 1em;
  height: 1em;
  display: inline-block;
  vertical-align: -0.16em;
  color: currentColor;
  flex-shrink: 0;
}
</style>
