<template>
  <component
    :is="IconComponent"
    class="app-icon"
    :size="Number(size)"
    :stroke-width="strokeWidth"
    aria-hidden="true"
  />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import {
  Activity,
  AlertTriangle,
  Apple,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  BadgeCheck,
  Banana,
  Banknote,
  BarChart3,
  Bean,
  Beer,
  Bell,
  BookOpen,
  Bot,
  BottleWine,
  Boxes,
  Brain,
  Briefcase,
  Building2,
  Cake,
  CakeSlice,
  Calculator,
  Calendar,
  Candy,
  CandyCane,
  Check,
  Cherry,
  Citrus,
  ClipboardList,
  Clock,
  Coffee,
  Coins,
  Cookie,
  Cpu,
  CreditCard,
  Croissant,
  CupSoda,
  Database,
  Donut,
  Download,
  Drumstick,
  Egg,
  EggFried,
  Eye,
  EyeOff,
  FileText,
  Fish,
  Flame,
  FlameKindling,
  FlaskConical,
  ForkKnife,
  ForkKnifeCrossed,
  Gauge,
  GlassWater,
  Grape,
  HardDrive,
  History,
  IceCream,
  IceCream2,
  IceCreamBowl,
  IceCreamCone,
  Keyboard,
  Key,
  Layers,
  LayoutDashboard,
  Lock,
  LogOut,
  Maximize2,
  Menu,
  Milk,
  Minimize2,
  MinusCircle,
  Monitor,
  Moon,
  MoonStar,
  Nut,
  Package,
  Palette,
  Pencil,
  Pizza,
  Plus,
  Popcorn,
  Printer,
  Receipt,
  ReceiptText,
  RefreshCw,
  Salad,
  Sandwich,
  Save,
  Scale,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sliders,
  SlidersHorizontal,
  Soup,
  Sparkle,
  Sparkles,
  Stars,
  Store,
  Sun,
  Tag,
  Tags,
  Timer,
  TimerOff,
  Trash2,
  TrendingDown,
  TrendingUp,
  Truck,
  Upload,
  UserCheck,
  UserCog,
  Users,
  Utensils,
  UtensilsCrossed,
  Volume2,
  WalletCards,
  Warehouse,
  Wheat,
  Wine,
  X,
  Zap,
} from 'lucide-vue-next';

const props = defineProps({
  name: { type: String, default: 'dashboard' },
  size: { type: [Number, String], default: 20 },
  strokeWidth: { type: [Number, String], default: 2 },
});

const icons: Record<string, any> = {
  // Navigation & Core
  dashboard: LayoutDashboard,
  gauge: Gauge,
  shop: Store,
  sales: ReceiptText,
  coffee: Coffee,
  zap: Zap,
  bot: Bot,
  cpu: Cpu,
  products: Package,
  purchases: ShoppingCart,
  inventory: Boxes,
  costs: Calculator,
  recipes: ClipboardList,
  stocktake: ClipboardList,
  customers: Users,
  invoices: FileText,
  quote: FileText,
  quotes: UtensilsCrossed,
  expenses: WalletCards,
  suppliers: Truck,
  reports: BarChart3,
  users: ShieldCheck,
  settings: Settings,
  operations: Activity,
  hr: Briefcase,
  search: Search,
  money: WalletCards,
  cash: Banknote,
  wallet: WalletCards,
  building: Building2,
  company: Building2,
  categories: Layers,
  category: Tag,
  tags: Tags,
  tag: Tag,
  unit: Scale,
  units: Scale,
  scale: Scale,
  sound: Volume2,
  volume: Volume2,
  shortcuts: Keyboard,
  keyboard: Keyboard,
  backup: HardDrive,
  database: Database,
  history: History,
  lock: Lock,
  shield: Shield,
  print: Printer,
  printer: Printer,
  palette: Palette,
  theme: Palette,
  monitor: Monitor,
  warehouse: Warehouse,
  flask: FlaskConical,
  send: Send,
  brain: Brain,
  bell: Bell,
  upload: Upload,
  download: Download,
  plus: Plus,
  add: Plus,
  edit: Pencil,
  delete: Trash2,
  trash: Trash2,
  save: Save,
  close: X,
  check: Check,
  warning: AlertTriangle,
  moon: Moon,
  moonStar: MoonStar,
  sun: Sun,
  menu: Menu,
  logout: LogOut,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowRightLeft: ArrowRightLeft,
  calendar: Calendar,
  clock: Clock,
  coins: Coins,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  userCheck: UserCheck,
  userCog: UserCog,
  receipt: Receipt,
  copilot: Sparkles,
  eye: Eye,
  eyeOff: EyeOff,
  maximize: Maximize2,
  minimize: Minimize2,
  timer: Timer,
  timerOff: TimerOff,
  refresh: RefreshCw,
  refreshCw: RefreshCw,
  minusCircle: MinusCircle,
  fileText: FileText,
  activity: Activity,
  sliders: SlidersHorizontal,
  shoppingBag: ShoppingBag,
  bookOpen: BookOpen,
  badge: BadgeCheck,
  creditCard: CreditCard,
  key: Key,

  // Food, Beverage, Coffee & Cafe POS Icons
  bean: Bean,
  beans: Bean,
  cupSoda: CupSoda,
  cookie: Cookie,
  cookies: Cookie,
  cake: Cake,
  cakeSlice: CakeSlice,
  iceCream: IceCream,
  iceCream2: IceCream2,
  iceCreamCone: IceCreamCone,
  iceCreamBowl: IceCreamBowl,
  milk: Milk,
  flame: Flame,
  flameKindling: FlameKindling,
  citrus: Citrus,
  glassWater: GlassWater,
  utensils: Utensils,
  utensilsCrossed: UtensilsCrossed,
  forkKnife: ForkKnife,
  forkKnifeCrossed: ForkKnifeCrossed,
  sandwich: Sandwich,
  croissant: Croissant,
  donut: Donut,
  wheat: Wheat,
  wine: Wine,
  bottleWine: BottleWine,
  apple: Apple,
  banana: Banana,
  cherry: Cherry,
  grape: Grape,
  pizza: Pizza,
  popcorn: Popcorn,
  salad: Salad,
  soup: Soup,
  candy: Candy,
  candyCane: CandyCane,
  beer: Beer,
  nut: Nut,
  nuts: Nut,
  drumstick: Drumstick,
  egg: Egg,
  eggFried: EggFried,
  fish: Fish,
  sparkle: Sparkle,
  sparkles: Sparkles,
  stars: Stars,
};

const aliases: Record<string, string> = {
  // Alias mappings (Material design / kebab-case / snake_case -> Lucide & common names)
  '+': 'plus',
  product: 'products',
  invoice: 'invoices',
  supplier: 'suppliers',
  expense: 'expenses',
  user: 'users',
  chart: 'reports',
  calculator: 'costs',
  'file-text': 'fileText',
  'refresh-cw': 'refreshCw',
  'minus-circle': 'minusCircle',
  'arrow-left': 'arrowLeft',
  'arrow-right': 'arrowRight',
  'trending-up': 'trendingUp',
  'trending-down': 'trendingDown',
  'eye-off': 'eyeOff',
  'timer-off': 'timerOff',
  pos: 'shop',
  shopping_cart: 'purchases',
  inventory_2: 'inventory',
  sync_alt: 'refreshCw',
  shopping_bag: 'shoppingBag',
  payments: 'money',
  group: 'customers',
  local_shipping: 'suppliers',
  menu_book: 'recipes',
  bar_chart: 'reports',
  manage_accounts: 'userCog',
  sell: 'category',

  // Food & Beverage Aliases
  'cup-soda': 'cupSoda',
  soda: 'cupSoda',
  juice: 'cupSoda',
  drink: 'cupSoda',
  cold_drink: 'cupSoda',
  'cake-slice': 'cakeSlice',
  'ice-cream': 'iceCream',
  icecream: 'iceCream',
  ice: 'iceCream',
  'ice-cream-cone': 'iceCreamCone',
  'ice-cream-bowl': 'iceCreamBowl',
  'glass-water': 'glassWater',
  water: 'glassWater',
  mineral_water: 'glassWater',
  glass: 'glassWater',
  'fork-knife': 'forkKnife',
  'fork-knife-crossed': 'forkKnifeCrossed',
  pastry: 'croissant',
  doughnut: 'donut',
  'candy-cane': 'candyCane',
  'moon-star': 'moonStar',
  'bottle-wine': 'bottleWine',
  'flame-kindling': 'flameKindling',
  fire: 'flame',
  hot: 'flame',
  spicy: 'flame',
  lemon: 'citrus',
  orange: 'citrus',
  fruit: 'apple',
  bread: 'croissant',
  snack: 'popcorn',
  dessert: 'cake',
  sweets: 'candy',
  tea: 'coffee',
  herbs: 'wheat',
};

const IconComponent = computed(() => {
  const raw = props.name || 'dashboard';
  const key = aliases[raw] || raw;
  return icons[key] || icons.dashboard;
});
</script>

<style scoped>
.app-icon {
  width: 1em;
  height: 1em;
  display: inline-block;
  vertical-align: -0.16em;
  color: currentColor;
  flex-shrink: 0;
}
</style>
